server:
  port: 9000
  

spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/angel
    driver-class-name: com.mysql.jdbc.Driver 
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  